package org.example.Aapuntes;

public class hashcodeEquals {
    //PARA QUE LAS LISTAS SET Y LOS MAPAS QUE CONTIENEN OBJETOS CREADOS POR MI NO TENGAN REPETIDOS,
    //HAY QUE SOBREESCRIBIR EL EQUALS Y HASHCODE, PARA QUE SE TENGAN EN CUENTA ESOS ATRIBUTOS PARA SABER
    //QUE LOS OBJETOS SON IGUALES.
}
